version: '3'

services:
  database:
    image: mariadb
    volumes:
    - ${DB_PATH}:/var/lib/mysql
    ports:
    - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TZ}
  site:
    build: ./
    ports:
    - 83:80
    environment:
      TZ: ${TZ}
    expose:
    - 83
    volumes:
    - ./:/usr/share/nginx/html
    links:
    - database
