<template>
    <div>
        <section_header_especialidades/>
        <section_studio_especialidades/>
        <section_desarrollo_especialidades/>
        <section_start_especialidades/>
        <section_newsletter_especialidades/>
        <section_redes_especialidades/>
        <section_cms_especialidades/>
        <section_design_especialidades/>
        <section_proceso_especialidades/>
    </div>
</template>
